[[main]]
  name = "الرئيسية"
  pageRef = "/"
  weight = 10

[[main]]
  name = "المدونة"
  pageRef = "/blog"
  weight = 20

[[main]]
  name = "حول"
  pageRef = "/about"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/ihabnk"
  weight = 200

[[footer]]
  name = "التصنيفات"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "الكتّاب"
  pageRef = "authors"
  weight = 20
